language: python
sudo: false
env:
  global:
    - secure: "KxLxbVhjY9WJX5t43yN6OHel6140Wb8ap6yy6Uieys0I4IPUulLIPAE/u7qeu3ObMLytZjASHFoNNFZ28u4O4oYf/IfAwSJdFr3v4fun1HTza4EZrXKBjbtRarzjWlfSRjwv8IbxLDi/aPX7vo2gkTyTrvu1LWWCfvhF2tbNTZVZxP3m7F778oW4EfsJCNnHvyscbsRW8Z+ApGjYjdJa97BUYS7nr3Ju5z0wkc3EmTbu6TDKZjeN5jOcidGulBJWx8UUWShyUwU+lrc2r4oQsca9VkBGaVls1Fc3l8ovrrU4Bd+/x7xYOPYmNhDQ3HPkUbD5PrMjrafKm4tDC+BJACP+WeMrr94BKSlNEdGHWeqgPwNkhWNvWmITowq79WEGcCRhwPV/yLXY2HxeOqrq7PiQ8SHCfUp3TyQ015IY7OAGPJ3wnkKkzxOwYgY7A9rEJGOA6Rwv2Jaae/rVoOKWv+5uIaB2zVeXdplaiL5sEe4rNbFDU5N2znQjhx1TmJqaGRcuSdvJVNUrS8MXPpkkmGgQpe9aTaAauTzHCodBWpuRrTIE5uIfOGBjzwN7WCSJtSXPZ32SM4R09Ar2ZD/0xdjUoCZH9JttTghbX8TF7/QG5GdhaMoqbnmFkVMhNPDg0WG2+YqHN4QFB4jEEZGHILx4Vclqb7X6QyAG289NUkU="
  matrix:
    - CUTTING_EDGE=true

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/matplotlib

services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server

python:
  - 3.5
  - 3.6
before_install:
  - "export DISPLAY=:99.0"
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/mc
  - export PATH=~/mc/bin:$PATH
  - conda update conda --yes
  - export CONDARC=ci/condarc


install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda create --yes -n testenv python=3.6 pytest codecov coverage xlrd xlsxwriter pymongo flake8 pandas -c conda-forge
  - source activate testenv

script:
  - set -e
  - coverage run run_tests.py
  - coverage report -m
  - codecov
  - flake8 sampledb
  - conda install --yes sphinx sphinx_rtd_theme
  - pip install git+git://github.com/drdoctr/doctr.git
  - cd docs
  - make html
  - cd ..
  - doctr deploy . --built-docs ./docs/_build/html;

